# ML Linear Regression 

In [5]:
import pandas as pd

In [10]:
df=pd.DataFrame({"X":[1,2,3,4,5],
                "y":[6,7,8,9,10]})
df

X   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [14]:
X=df[["X"]]
y=df.y

# Modelling

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

LinearRegression()

In [17]:
model.intercept_

4.999999999999999

In [20]:
model.coef_

array([1.])

In [22]:
#y=bo+b1x = 5+1(x)=5+x

# Prediction

In [26]:
ypred=model.predict(x)
ypred

array([ 6.,  7.,  8.,  9., 10.])

In [28]:
y

0     6
1     7
2     8
3     9
4    10
Name: y, dtype: int64

# Evaluation

In [31]:
from sklearn.metrics import mean_squared_error

mse= mean_squared_error(y,ypred)
mse

1.5777218104420237e-31

In [34]:
import numpy as np
rmse= np.sqrt(mse)
rmse

3.9720546451956367e-16

# EXAMPLE 2

In [68]:
import pandas as pd
df=pd.DataFrame({"U":[5,10,15,20,25],
                "v":[25,31,35,40,45]})
df

U   v
0   5  25
1  10  31
2  15  35
3  20  40
4  25  45

In [69]:
U=df[["U"]]
v=df.v

In [70]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(U,v)


LinearRegression()

In [71]:
model.intercept_


20.500000000000004

In [72]:
model.coef_

array([0.98])

In [76]:
vpred=model.predict(U)
vpred

array([25.4, 30.3, 35.2, 40.1, 45. ])

In [74]:
v

0    25
1    31
2    35
3    40
4    45
Name: v, dtype: int64

In [77]:
from sklearn.metrics import mean_squared_error

mse= mean_squared_error(v,vpred)
mse

0.1400000000000003

In [78]:
import numpy as np
rmse= np.sqrt(mse)
rmse

0.37416573867739455