# Train_Test_Split: Model Evaluation : Croos validation : Overfitting : Underfitting

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("homeprices.csv")
df

sno       town  area    price
0     0    Chennai  2600  5500000
1     1    Chennai  3000  5650000
2     2    Chennai  3200  6100000
3     3    Chennai  3600  6800000
4     4   Banglore  2600  5850000
5     5   Banglore  2800  6150000
6     6   Banglore  3300  6500000
7     7   Banglore  3600  7100000
8     8  Hyderabad  2600  5750000
9     9  Hyderabad  2900  6000000
10   10  Hyderabad  3100  6200000
11   11  Hyderabad  3600  6950000

In [5]:
df_dum=pd.get_dummies(df,drop_first=True)
df_dum 

sno  area    price  town_Chennai  town_Hyderabad
0     0  2600  5500000             1               0
1     1  3000  5650000             1               0
2     2  3200  6100000             1               0
3     3  3600  6800000             1               0
4     4  2600  5850000             0               0
5     5  2800  6150000             0               0
6     6  3300  6500000             0               0
7     7  3600  7100000             0               0
8     8  2600  5750000             0               1
9     9  2900  6000000             0               1
10   10  3100  6200000             0               1
11   11  3600  6950000             0               1

In [10]:
X=df_dum.drop('price',axis='columns') #Independent variable (X)
X

sno  area  town_Chennai  town_Hyderabad
0     0  2600             1               0
1     1  3000             1               0
2     2  3200             1               0
3     3  3600             1               0
4     4  2600             0               0
5     5  2800             0               0
6     6  3300             0               0
7     7  3600             0               0
8     8  2600             0               1
9     9  2900             0               1
10   10  3100             0               1
11   11  3600             0               1

In [9]:
y=df_dum.price #Dependent Variable (Y)
y

0     5500000
1     5650000
2     6100000
3     6800000
4     5850000
5     6150000
6     6500000
7     7100000
8     5750000
9     6000000
10    6200000
11    6950000
Name: price, dtype: int64

In [12]:
from sklearn.model_selection  import train_test_split

In [17]:
X_train,X_test=train_test_split(X,test_size=0.3)
print(X_train)
print(X_test)

    sno  area  town_Chennai  town_Hyderabad
0     0  2600             1               0
7     7  3600             0               0
11   11  3600             0               1
4     4  2600             0               0
1     1  3000             1               0
5     5  2800             0               0
3     3  3600             1               0
8     8  2600             0               1
    sno  area  town_Chennai  town_Hyderabad
2     2  3200             1               0
6     6  3300             0               0
10   10  3100             0               1
9     9  2900             0               1


In [15]:
y_train,y_test=train_test_split(y,test_size=0.3)
print(y_train)
print(y_test)

10    6200000
4     5850000
5     6150000
2     6100000
6     6500000
1     5650000
7     7100000
11    6950000
Name: price, dtype: int64
9    6000000
8    5750000
3    6800000
0    5500000
Name: price, dtype: int64


In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
print(X_train)

    sno  area  town_Chennai  town_Hyderabad
5     5  2800             0               0
2     2  3200             1               0
1     1  3000             1               0
11   11  3600             0               1
4     4  2600             0               0
7     7  3600             0               0
3     3  3600             1               0
6     6  3300             0               0


In [26]:
y_train

5     6150000
2     6100000
1     5650000
11    6950000
4     5850000
7     7100000
3     6800000
6     6500000
Name: price, dtype: int64

In [27]:
y_test


10    6200000
9     6000000
0     5500000
8     5750000
Name: price, dtype: int64

In [24]:
X_test

sno  area  town_Chennai  town_Hyderabad
11   11  3600             0               1
1     1  3000             1               0
5     5  2800             0               0
6     6  3300             0               0

In [30]:
#Example

In [32]:
import pandas as pd


In [34]:
df=pd.DataFrame({"X":[1,2,3,4,5],"y":[6,7,8,9,10]})
df

X   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [35]:
X=df[["X"]]
y=df[["y"]]

In [37]:
X

X
0  1
1  2
2  3
3  4
4  5

In [38]:
y

y
0   6
1   7
2   8
3   9
4  10

In [40]:
from sklearn.model_selection import train_test_split
X_tr,X_te,y_tr,y_te=train_test_split(X,y,train_size=0.8)

In [41]:
X_tr

X
4  5
3  4
1  2
0  1

In [43]:
X_te

X
2  3

In [45]:
y_tr

y
4  10
3   9
1   7
0   6

In [46]:
y_te

y
2  8

In [48]:
#Apply regression Technique

In [50]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(X_tr,y_tr)

LinearRegression()

In [52]:
model.intercept_

array([5.])

In [54]:
model.coef_

array([[1.]])

In [55]:
model.predict(X_tr)

array([[10.],
       [ 9.],
       [ 7.],
       [ 6.]])

In [57]:
model.predict(X_te)

array([[8.]])